import Navbar from "@/components/UI/navbar";
import "./globals.css";
import Footer from "@/components/UI/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>

        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        
      </body>
    </html>
  );
}
